name: CD

# CI 워크플로우가 성공적으로 완료된 후에만 실행
on:
  workflow_run:
    workflows: ["CI"] 
    types:
      - completed
    branches:
      - main 

jobs:
  deploy:
    # CI 워크플로우가 성공한 경우에만 실행
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: platypus3036/matching-service:latest
      
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 이미지 풀
            docker pull platypus3036/matching-service:latest
            
            # 기존 컨테이너 중지 및 삭제
            docker stop matching-service || true
            docker rm matching-service || true
            
            # 새 컨테이너 실행
            docker run -d \
              --name matching-service \
              --restart unless-stopped \
              --memory="3g" \
              --memory-reservation="2.5g" \
              --cpus=1.8 \
              -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
              -e RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }} \
              -e RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }} \
              -e RABBITMQ_USERNAME=${{ secrets.RABBITMQ_USERNAME }} \
              -e RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }} \
              platypus3036/matching-service:latest
            
